### ISSUE TITLE
Beast Bot Site

### ISSUE THREAD

**Issue by bas1c-codes** [ShadowEmperorYT/Status#3]
start: 2021-016-11T12:00:00.220Z
end: 2021-16-11T5:00:00.220Z
expectedDown: Beast Bot Site

The site is in domain error thingy we will fix the issue as soon as we can

**Comment by ShadowEmperorYT** [comment]
start: 2021-016-11T12:00:00.220Z
end: 2021-16-11T5:00:00.220Z
expectedDown: Beast Bot Site

**Comment by bas1c-codes** [comment]
tart: 2021-016-11T12:00:00.220Z
end: 2021-16-11T5:00:00.220Z
expectedDown: Beast Bot Site

The site is in domain error thingy we will fix the issue as soon as we can
